### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by x656** [FloatProtocol/float-bot-template#1]
getting the following error, for you know where i can find this module?

```
$ /Users/x/src/float-bot-template/node_modules/.bin/hardhat --network mainnet last
An unexpected error occurred:

hardhat.config.ts:5:36 - error TS2307: Cannot find module '@floatprotocol/float-contracts/deployments/mainnet/AuctionHouse.json' or its corresponding type declarations.

5 import auctionHouseDeployment from "@floatprotocol/float-contracts/deployments/mainnet/AuctionHouse.json";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
```

**Comment by floatcoder** [comment]
You likely need to install dependencies first:
```
yarn
# or
npm install
```

**Comment by floatcoder** [comment]
As to where the module is - https://www.npmjs.com/package/@floatprotocol/float-contracts
https://unpkg.com/browse/@floatprotocol/float-contracts@1.0.2/deployments/mainnet/AuctionHouse.json

**Comment by floatcoder** [comment]
Hope that helped, let me know if you're still having trouble.

**Comment by x656** [comment]
@floatcoder yup that did it,
saw you added dep to https://github.com/FloatProtocol/float-bot-template/blob/main/package.json
thanks for your help!
